language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -c 'CREATE DATABASE send_test' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
  - codecov